### ISSUE TITLE
Add labeled links to the nexus graph

### ISSUE THREAD

**Issue by NeilAllavarpu** [ScandinavianSection-UCLA/Nexus2#123]
Probably gonna be very difficult, but add a label to each of the links describing the connection. Ex: A link from Jens (Bitte Jens) Kristensen to 150 - 0.01 - DS_II_D_5 would be labeled as "wrote this story), or if it was from story to author it could be written as "was written by this person".

**Comment by tango2** [comment]
Told as opposed to wrote—these are all just people sitting around orally telling stories. But labeling these might be messy/hard. Maybe either rollover or a key to line types? Eg solid = told, dotted=told at; dash = mentions place

Sent by my pet goat

**Comment by avearle** [comment]
@tango2 Here is a list of primary links. Let me know if any need to be modified or added.

[person] < told > [story]
[person] < was born at > [place]
[person] < died at > [place]
[story] < was recorded at > [place]
[story] < mentions > [place]
[story] < was recorded during > [fieldtrip]
