### ISSUE TITLE
Clicking on the book chapters should take you to the selected chapter

### ISSUE THREAD

**Issue by NeilAllavarpu** [ScandinavianSection-UCLA/Nexus2#129]
Currently, clicking on chapters via the top right book icon only gets you to the book view. It should take you to the selected chapter, like how you can with the double bar icon in the top left of the book view

**Comment by dhuangg** [comment]
On Chrome, opening multiple chapter tabs doesn't take you to the new chapters

**Comment by NeilAllavarpu** [comment]
Closed along with #137
