### ISSUE TITLE
Allow all 3 of the side menus on Story View to be collapsed at once

### ISSUE THREAD

**Issue by NeilAllavarpu** [ScandinavianSection-UCLA/Nexus2#143]
Why have a minus sign when it doesn't do anything?

<img width="1280" alt="screen shot 2018-11-15 at 16 24 06" src="https://user-images.githubusercontent.com/13577797/48590045-ebc3af80-e8f2-11e8-8b73-550f4e7d0432.png">

**Comment by dhuangg** [comment]
We don't want to collapse all of the fields on the side view. We always want one of them open, so we should just remove the minus sign from the tabs.
