### ISSUE TITLE
Bibliographical references are rendered as plaintext instead of HTML

### ISSUE THREAD

**Issue by NeilAllavarpu** [ScandinavianSection-UCLA/Nexus2#159]
I'm assuming those `<i>` tags aren't supposed to be part of the reference but should italicize the text within them.

<img width="1280" alt="screen shot 2018-11-19 at 11 05 55" src="https://user-images.githubusercontent.com/13577797/48729045-7bb37300-ebeb-11e8-9a37-f693f43a5cb3.png">

**Comment by dhuangg** [comment]
this is an issue @shiv is working on. there's an existing ticket for it

**Comment by dhuangg** [comment]
#45 addresses this issue

**Comment by NeilAllavarpu** [comment]
Oops, did not see that issue
