### ISSUE TITLE
Drag and drop broken on Firefox

### ISSUE THREAD

**Issue by NeilAllavarpu** [ScandinavianSection-UCLA/Nexus2#160]
Why can't all browsers just be the same...

<img width="1280" alt="screen shot 2018-11-19 at 14 31 25" src="https://user-images.githubusercontent.com/13577797/48739164-f7231d80-ec07-11e8-80f4-5f778983a355.png">

**Comment by tango2** [comment]
🤣🤣🤣

Sent by my pet goat
