### ISSUE TITLE
QuotaExceededError in Safari

### ISSUE THREAD

**Issue by shivanshug14** [ScandinavianSection-UCLA/Nexus2#17]
So far this has only occurred in safari. Firefox/chrome work fine.

In the home tab, when clicking elements on the navigation column on the left hand side, the following bug is displayed 
![screen shot 2018-06-03 at 3 29 41 pm](https://user-images.githubusercontent.com/18354771/40891908-36ac2a2c-6743-11e8-81b5-70d0c82dff83.png)

**Comment by dhuangg** [comment]
@shivanshug14 can you pull this version and see if you  still get this issue?
