### ISSUE TITLE
Highlight similar nodes feature

### ISSUE THREAD

**Issue by dhuangg** [ScandinavianSection-UCLA/Nexus2#175]
When the user hovers over the legend in the user nexus, the responding type of nodes should be highlighted.
<img width="1428" alt="screen shot 2018-12-24 at 12 42 21 pm" src="https://user-images.githubusercontent.com/12959959/50406397-6052ff00-0779-11e9-8e08-0a0d29cc2c7a.png">

[Documentation for `react-d3-graph`](https://danielcaldas.github.io/react-d3-graph/docs/index.html)

**Comment by NeilAllavarpu** [comment]
As far as I can tell, I can use any of [these](https://goodguydaniel.com/react-d3-graph/docs/index.html#config-node) properties that have a magnifying glass to distinguish nodes when a hover is triggered. Would changing the opacity or size of the nodes suffice?
