### ISSUE TITLE
Set-up docker container

### ISSUE THREAD

**Issue by dhuangg** [ScandinavianSection-UCLA/Nexus2#180]
Create docker container for react and jenkins

[Tutorial Link from Jenkins](https://jenkins.io/doc/tutorials/build-a-node-js-and-react-app-with-npm/)

**Comment by dhuangg** [comment]
@tango2: I saw some convos about docker--it occurred to me that, if you get that working, it might be fun to experiment with elastic beanstalk and make the entire thing a serverless cloud service: https://medium.com/@sommershurbaji/deploying-a-docker-container-to-aws-with-elastic-beanstalk-28adfd6e7e95  I'm not sure how that would work if we wanted to have a data entry/editing/upload aspect, but I'm sure there must be something possible.

**Comment by dhuangg** [comment]
> 
<sub>[View in Slack](https://uclanexus2.slack.com/archives/CA4930F47/p1548994013000100)</sub>

**Comment by dhuangg** [comment]
[Tutorial for setting-up docker container with Apache](https://www.tecmint.com/install-apache-web-server-in-a-docker-container/)

**Comment by dhuangg** [comment]
@shivanshug14 following [this tutorial](https://medium.com/greedygame-engineering/so-you-want-to-dockerize-your-react-app-64fbbb74c217) (case 2) to upload our existing react project to a new docker contianer

**Comment by shivanshug14** [comment]
https://cloud.docker.com/u/uclanexus2/repository/docker/uclanexus2/nexus2-v0.1
