### ISSUE TITLE
clean up sessionStorage

### ISSUE THREAD

**Issue by dhuangg** [ScandinavianSection-UCLA/Nexus2#197]
Over time, we've dumped a lot of things into sessionStorage. Do an audit of what we store in sessionStorage now.

View all key value pairs in session storage through this code: 
```
for(var i=0, len=sessionStorage.length; i<len; i++) {
    var key = sessionStorage.key(i);
    var value = sessionStorage[key];
    console.log(key + " => " + value);
}
```
Remove anything that we don't need/look up where we're setting them in the code

**Comment by shivanshug14** [comment]
1. `SelectedNavOntology => {"data":"Stories"}`

2. ```TabViewerSessionState => {"views":[{"active":false,"id":0,"name":"Home","type":"Home","color":null},{"id":5,"active":false,"name":"150 - 1.02 - DSkv_0_11e","type":"Stories","color":null,"pinned":false},{"id":2,"active":true,"name":"3. Evald Tang Kristensen's Life and Work","type":"Book","color":null,"pinned":false}]}```

3. ```graphData => {"nodes":[{"id":"150 - 1.02 - DSkv_0_11e","color":"grey","item":{"story_id":5,"informant":{"id":150},"publication_info":"DSkv_0_11e","full_name":"150 - 1.02 - DSkv_0_11e","search_string":"DSkv_0_11e (5): Jens (Bitte Jens) Kristensen","place_recorded":{"id":147},"url":"data/stories/5.dfl","fieldtrip":{"id":1},"places_mentioned":null},"type":"Stories","itemID":5}],"links":[]}```

4. ```nodeCategories => {"Fieldtrips":[],"People":[],"Places":[],"Stories":[{"id":"150 - 1.02 - DSkv_0_11e","color":"grey","item":{"story_id":5,"informant":{"id":150},"publication_info":"DSkv_0_11e","full_name":"150 - 1.02 - DSkv_0_11e","search_string":"DSkv_0_11e (5): Jens (Bitte Jens) Kristensen","place_recorded":{"id":147},"url":"data/stories/5.dfl","fieldtrip":{"id":1},"places_mentioned":null},"type":"Stories","itemID":5}]}```
