### ISSUE TITLE
connection strings

### ISSUE THREAD

**Issue by tango2** [ScandinavianSection-UCLA/Nexus2#25]
Here are the connection strings for the tile services--same login info as before (I've put xxx in place of the password)--I'll work on getting a project specific login for the services so it doesn't have my personal account there:

low boards:
servicename=topo20_lave_maalebordsblade&client=arcGIS&request=GetCapabilities&service=WMS&version=1.1.1&login=tango1963&password=xxxxxxxxx&

high boards:
servicename=topo20_hoeje_maalebordsblade&client=arcGIS&request=GetCapabilities&service=WMS&version=1.1.1&login=tango1963&password=xxxxxxxxx&

prussian maps (these fill in southern Denmark on the high boards):
servicename=topo25_preussen_maalebordsblade&client=arcGIS&request=GetCapabilities&service=WMS&version=1.1.1&login=tango1963&password=xxxxxxxx&

**Comment by shivanshug14** [comment]
1. I've added the three tiles and it looks like high boards and the Danish layer (the very first WMS tile we added) are the same layers, so I've included just one of them
2. Still need to figure out how to display the Prussian layer simultaneously with the High Boards layer
