### ISSUE TITLE
Set Default Map

### ISSUE THREAD

**Issue by dhuangg** [ScandinavianSection-UCLA/Nexus2#28]
Right now, the MapView loads through all of the maps until the Prussian Map which is pretty limited in what it displays. Maybe it'd be better to set a default map that would display all of Denmark? 

## What the map looks like after loading everything
<img width="497" alt="screen shot 2018-06-12 at 10 51 51 am" src="https://user-images.githubusercontent.com/12959959/41307652-a4375b24-6e2e-11e8-8546-23a8c37ef214.png">

**Comment by tango2** [comment]
Yes, this is a good point. I think the opacity slider might help here--one could load something like the open street maps or some generic Danish map as the default base map, and then layers would be drawn over that base (always on) layer--the slider could then be adjusted to bring in the appropriate layer--of course, this always encourages feature creep: imagine an opacity slider for each layer : )
