### ISSUE TITLE
Add occupation to person info

### ISSUE THREAD

**Issue by dhuangg** [ScandinavianSection-UCLA/Nexus2#5]
The person's description currently includes date of birth/death/ other info. we need to add the person's occupation onto the person description based on [this chart](https://drive.google.com/open?id=1U7ikQJklHTG9qyKKBiQl2FMwa-VQiNFW)

<img width="921" alt="screen shot 2018-06-03 at 4 52 35 pm" src="https://user-images.githubusercontent.com/12959959/40891226-d53f58b0-674f-11e8-80d3-63b582469093.png">

**Comment by tango2** [comment]
Here is a translated list of the occupations in the data--csv file; let me know if there are questions.
[occupations_translated.txt](https://github.com/ScandinavianSection-UCLA/Nexus2/files/2087370/occupations_translated.txt)
