### ISSUE TITLE
Clicking on 'all' field trip crashes the app

### ISSUE THREAD

**Issue by NeilAllavarpu** [ScandinavianSection-UCLA/Nexus2#60]
<img width="1280" alt="Error Message" src="https://user-images.githubusercontent.com/13577797/46574907-0738b380-c960-11e8-9870-7f9204731f0c.png">

I went to Topic & Index Navigator > Fieldtrips > All (bottom fieldtrip).

**Comment by dhuangg** [comment]
@NeilAllavarpu I think this is supposed to combine all of the fieldtrip data into one. Perhaps @tango2 can provide some insights.
